services:
  - type: web
    name: binance-oi-monitor
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    healthCheckPath: /healthz
